version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: kimura-postgres
    environment:
      POSTGRES_USER: kimura
      POSTGRES_PASSWORD: kimura_secret
      POSTGRES_DB: kimura_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kimura"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kimura-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

  mailhog:
    image: mailhog/mailhog
    container_name: kimura-mailhog
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

volumes:
  pgdata:
  redisdata:
